# Default build settings
[build]
  command = "npm run website:prerender"
  functions = "dist/netlify"
  publish = "dist/website/browser"
  environment = { CYPRESS_INSTALL_BINARY = "false" }

# Override for PRs to deploy the dev app
[context.deploy-preview]
  command = "npm run build:preview && npm run website:news && npm run website:deploy-preview && cp -R dist/dev dist/website/browser/dev"
